// app-svelte/src/lib/components/singleConvertor/ResultDisplay.svelte
<script lang="ts">
	export let convertedAmount: number | null;
</script>

<div class="space-y-2">
	<!-- svelte-ignore a11y_label_has_associated_control -->
	<label class="block text-sm font-medium text-gray-700">Resultado</label>
	<input
		class="w-full rounded border px-3 py-2"
		value={convertedAmount !== null ? convertedAmount.toFixed(2) : ''}
		readonly
	/>
</div>

// app-vue/src/components/singleConverter/ResultDisplay.vue
<template>
  <div class="space-y-2">
    <Label>Resultado</Label>
    <Input :value="formattedResult" readonly />
  </div>
</template>

<script setup lang="ts">
import { computed, defineProps } from 'vue'
import { Label } from '@/components/ui/label'
import { Input } from '@/components/ui/input'

const props = defineProps<{
  result: number | null
}>()

const formattedResult = computed(() =>
  props.result !== null ? props.result.toFixed(2) : ''
)
</script>
